runtime_rg     = "runtimes-machines"
runtime_region = "westeurope"
#machinename             = "runtimemachine1"
#shared_image_definition = "en-windows-2019"
shared_image_gallery = "golden_image_gallery"
shared_image_rg      = "golden-image-factory-artifacts"
