---
# chrome extension cannot be enabled automatically:
# https://support.google.com/chrome/thread/9069715?hl=en
- name: Install UiPath Studio
  win_package:
    path: https://download.uipath.com/versions/20.4.3/UiPathStudio.msi
    arguments:
    - /quiet
    - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,StartupLauncher,RegisterService,JavaBridge,ChromeExtension
    state: present
    product_id: '{3067A978-2709-4976-8F50-6CD65A1DC380}'

- name: Install UiPath Remote Runtime
  win_package:
    path: https://download.uipath.com/versions/20.4.2/UiPathRemoteRuntime.msi
    arguments:
      - /quiet
      - ADDLOCAL=RemoteRuntime,RemoteRuntimeTask
    state: present
    product_id: '{299DBA4A-AB63-42EE-AF8C-EF020D2EB900}'

- name: Set service startup mode to auto and ensure it is started
  win_service:
    name: UiRobotSvc
    start_mode: auto
    state: started
