name: baking-the-image
resources:
  containers:
    - container: buildpacks-infra
      image: ghcr.io/mysticrenji/buildpacks-infra:v1.0.0

trigger:
  - main

variables:
  - group: infra_variables
  - name: tfWorkSpace
    value: $(Pipeline.Workspace)/s/

stages:
  - stage: "Terraform_Init"
    displayName: "Initialise Terraform"
    jobs:
      - job: Terraform_Init
        container: buildpacks-infra
        steps:
          - script: |
                terraform init
                terraform fmt
                terraform plan -var-file=auto.tfvars
                
            workingDirectory: $(Build.SourcesDirectory)/terraform
          # - task: Cache@2
          #   displayName: "Register TF providers"
          #   inputs:
          #     key: terraform | $(Agent.OS) | "$(Build.BuildNumber)" | $(Build.SourceVersion)"
          #     path: "$(tfWorkSpace)"